base_url: "https://www.saucedemo.com/"
credentials:
  valid_user:
    username: "standard_user"
    password: "secret_sauce"
  invalid_user:
    username: "test_user"
    password: "invalid"

product1: "Sauce Labs Backpack"
product2: "Sauce Labs Bolt T-Shirt"

first_name: "John"
last_name: "Doe"
postal_code: "11111"

headless: true
timeout: 10